const TOOL_HUB_ROOT_DIR = ".tool-hub";
const GENERATOR_DIR_NAME = "generator";
const METADATA_FILE_NAME = ".toolhub-generator.json";
const TEMPLATE_DIR_REL = "../templates/node-hello-app";
const TEMPLATE_DIR_RESOURCE_SEGMENTS = ["templates", "node-hello-app"];
const TEMPLATE_AGENTS_FILE_NAME = "AGENTS.md";
const TEMPLATE_AGENTS_ASSET_FILE_NAME = "node-hello-app-agents-template.txt";

const CHAT_TIMEOUT_MS = 240000;
const MAX_OUTPUT_CHARS = 2_000_000;
const MAX_FILE_READ_BYTES = 200000;
const TERMINAL_OUTPUT_MAX_CHARS = 200000;
const VERIFY_TIMEOUT_MS = 600000;
const VERIFY_OUTPUT_MAX_CHARS = 50000;
const DEFAULT_VERIFY_COMMAND = "node --check src/index.js";
const LEGACY_VERIFY_COMMAND = "pnpm typecheck";
const GENERATOR_VALIDATION_ERROR_PREFIX = "GENERATOR_VALIDATION_FAILED:";
const GENERATOR_VERIFY_ERROR_PREFIX = "GENERATOR_VERIFY_FAILED:";

module.exports = {
  CHAT_TIMEOUT_MS,
  DEFAULT_VERIFY_COMMAND,
  GENERATOR_DIR_NAME,
  GENERATOR_VALIDATION_ERROR_PREFIX,
  GENERATOR_VERIFY_ERROR_PREFIX,
  LEGACY_VERIFY_COMMAND,
  MAX_FILE_READ_BYTES,
  MAX_OUTPUT_CHARS,
  METADATA_FILE_NAME,
  TEMPLATE_AGENTS_ASSET_FILE_NAME,
  TEMPLATE_AGENTS_FILE_NAME,
  TEMPLATE_DIR_REL,
  TEMPLATE_DIR_RESOURCE_SEGMENTS,
  TERMINAL_OUTPUT_MAX_CHARS,
  TOOL_HUB_ROOT_DIR,
  VERIFY_OUTPUT_MAX_CHARS,
  VERIFY_TIMEOUT_MS,
};
